# Generated by Django 3.2.2 on 2022-06-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('ad_post', '0003_favoriteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
